### ISSUE TITLE
TODO Business Network Model

### ISSUE THREAD

**Issue by hounded** [hounded/propertyAgreementNetwork#2]
## TOP LEVEL REQUIREMENTS
- [x] finish cto 
- [ ] write logic
- [ ] define permissions acl 
## CTO
- [x] Has a vendor
- [x] Has a purchaser
- [x] Has a property
- [x] Has an agreement
- [x] Has an agreement with states (Proposal, Counter, Agreed) e.g. proposal-->counter-->proposal-->agreed
- [x] Has conditions that relate to the agreement
## Logic
- [ ] A vendor or a purchaser can set up an Agreement that will set Property parameters the propertyListing parameters and/or conditions. The party that creates the Agreement will have to invite the other party to the agreement.
- [ ] A purchaser can counter the Agreement changing the conditions and propertyListing variables
- [ ] A vendor can counter the Agreement changing the conditions and propertyListing variables
- [ ] A purchaser can agree to the Agreement
- [ ] A vendor can agree to the Agreement 
- [x] Add a setup script for testing purposes
- [ ] When agree is set by both parties the Agreement is finalised and no more transactions can take place. The status of the Agreement changes to agreed (If a change is required then a new agreement must be created??)
## Permissions 
- [ ] The party that creates the agreement can view and edit as defined by the logic 
- [ ] The invited party can view and edit as defined by the logic 
## Stretch goals 
- [ ] Allow both parties to agree on a third and/or four party to join the finalised agreement (aka lawyers)
