### ISSUE TITLE
TODO Hackathon Requirements

### ISSUE THREAD

**Issue by hounded** [hounded/propertyAgreementNetwork#3]
## Requirements to Submit to the Hackathon

- [x] Screencast with voice over (max 2 minutes)
- [x] Link to git repo 
- [x] 1 Paragraph writeup on problem
- [x] 1 Paragraph write up on solution
